language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

services:
  - mysql

before_script:
  - cp tests/config.php config.php
  - mysql -u root -e "CREATE DATABASE IF NOT EXISTS tracking;"
  - mysql -u root -e "CREATE USER 'track'@'localhost' IDENTIFIED BY 'password';"
  - mysql -u root -e "GRANT USAGE ON *.* TO 'track'@'localhost';"
  - mysql -u root -e "GRANT ALL PRIVILEGES ON tracking.* TO 'track'@'localhost';"
  - mysql -u root -e "FLUSH PRIVILEGES;"
  - mysql -u track -ppassword tracking < database.sql
  - mysql -u track -ppassword tracking < tests/test_data.sql

script:
  - phpunit -v tests/

notifications:
  email: false
